### ISSUE TITLE
Header组件的一个小问题

### ISSUE THREAD

**Issue by Mrsususu** [jinjiaxing/react-template-easily#12]
你好，最近小项目有尝试您的脚手架。在使用时发现一个小问题，Header组件中，您返回路由使用了this.context.router.goBack()，在react-router-dom的v4版本中，该方法似乎已经放置到了history方法下，即为this.context.router.history.goBack()，不知是否是这样？

**Comment by jasonjin-ai** [comment]
是的，谢谢提醒，部分组件是在react-router老版本中写的，在升级router v4的时候，有一些组件更新遗漏

**Comment by jasonjin-ai** [comment]
该问题已经更新，请查看最新代码
